<a href="https://colab.research.google.com/github/gilvandrocesardemedeiros/ClimatePrediction/blob/master/Predict_Rain_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Importando bibliotecas
import pandas as pd
import numpy as np
from datetime import datetime
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt


In [0]:
#Nomes para as colunas
columns = ["Estacao","Data","Hora","Prec","TempMax","TempMin","Insolacao","EvapoPiche","TempCompMedia",
           "UmidRelatMedia", "VelocVento", "Missing"]

#Tipos de dados em cada coluna
types = {"Hora":np.uint16,"Prec":np.float64,"TempMax":np.float64,"TempMin":np.float64,"Insolacao":np.float64,
         "EvapoPiche":np.float64,"TempCompMedia":np.float64,"UmidRelatMedia":np.float64,"VelocVento":np.float64}

#Leitura do arquivo csv
dataSet = pd.read_csv("https://github.com/gilvandrocesardemedeiros/ClimatePrediction/raw/master/Dados_INMET/Diarios/INMET-Dados_Diarios_Natal_1968-2018.csv",
                      sep=';',skiprows=48, nrows = 27003, usecols = columns[1:11], names=columns, dtype = types)

In [0]:
#Transformando data em variável do tipo datetime
dataSet["Data"] = pd.to_datetime(dataSet["Data"], format = "%d/%m/%Y")

In [42]:
#Verificando dados
dataSet.head()

Data  Hora  Prec  TempMax  TempMin  Insolacao  EvapoPiche  \
0 1968-01-01     0   NaN     30.6      NaN       11.1         4.4   
1 1968-01-01  1200   0.0      NaN     21.4        NaN         NaN   
2 1968-01-02     0   NaN     31.0      NaN       11.9         6.5   
3 1968-01-02  1200   0.0      NaN     19.6        NaN         NaN   
4 1968-01-03     0   NaN     31.6      NaN       11.3         5.0   

   TempCompMedia  UmidRelatMedia  VelocVento  
0          25.14           73.50    2.666667  
1            NaN             NaN         NaN  
2          24.92           74.75    1.666667  
3            NaN             NaN         NaN  
4          24.90           77.25    2.333333

In [43]:
#Verificando o tipo dos dados
dataSet.dtypes

Data              datetime64[ns]
Hora                      uint16
Prec                     float64
TempMax                  float64
TempMin                  float64
Insolacao                float64
EvapoPiche               float64
TempCompMedia            float64
UmidRelatMedia           float64
VelocVento               float64
dtype: object

In [0]:
#Separando os dados em dois dataframes, um para as 00:00 h e outro para as 12:00 h
dataSet00, dataSet12 = dataSet[dataSet["Hora"] == 0], dataSet[dataSet["Hora"] == 1200]

In [45]:
#Verificando dataframe para os dados disponibilizados às 00:00 h
dataSet00.head()

Data  Hora  Prec  TempMax  TempMin  Insolacao  EvapoPiche  \
0 1968-01-01     0   NaN     30.6      NaN       11.1         4.4   
2 1968-01-02     0   NaN     31.0      NaN       11.9         6.5   
4 1968-01-03     0   NaN     31.6      NaN       11.3         5.0   
6 1968-01-04     0   NaN     31.2      NaN       10.3         4.0   
8 1968-01-05     0   NaN     30.8      NaN       11.0         4.2   

   TempCompMedia  UmidRelatMedia  VelocVento  
0          25.14           73.50    2.666667  
2          24.92           74.75    1.666667  
4          24.90           77.25    2.333333  
6          24.82           80.75    3.666667  
8          24.78           76.00    4.000000

In [46]:
#Verificando dataframe para os dados disponibilizados às 12:00 h
dataSet12.head()

Data  Hora  Prec  TempMax  TempMin  Insolacao  EvapoPiche  \
1 1968-01-01  1200   0.0      NaN     21.4        NaN         NaN   
3 1968-01-02  1200   0.0      NaN     19.6        NaN         NaN   
5 1968-01-03  1200   0.0      NaN     18.5        NaN         NaN   
7 1968-01-04  1200   0.0      NaN     20.7        NaN         NaN   
9 1968-01-05  1200   0.0      NaN     19.9        NaN         NaN   

   TempCompMedia  UmidRelatMedia  VelocVento  
1            NaN             NaN         NaN  
3            NaN             NaN         NaN  
5            NaN             NaN         NaN  
7            NaN             NaN         NaN  
9            NaN             NaN         NaN

In [0]:
#Transformando a data no índice de cada dataframe
dataSet00 = dataSet00.set_index("Data")
dataSet12 = dataSet12.set_index("Data")

In [0]:
#Descartando a coluna "Hora"
dataSet00, dataSet12 = dataSet00.drop(columns = "Hora"), dataSet12.drop(columns = "Hora")

In [49]:
#Juntando os dados em um mesmo dataframe (no caso, o dataSet00)
for i in dataSet00.index:
    try:
        dataSet00["Prec"].loc[i] = dataSet12["Prec"].loc[i]
        dataSet00["TempMin"].loc[i] = dataSet12["TempMin"].loc[i]
    except:
        print("Data " + str(i.day) + "/" + str(i.month) + "/" + str(i.year) + " Não encontrada!")

Data 5/7/1986 Não encontrada!
Data 20/7/1986 Não encontrada!
Data 3/6/1989 Não encontrada!
Data 12/6/1989 Não encontrada!
Data 4/12/1992 Não encontrada!
Data 26/5/2018 Não encontrada!
Data 1/8/2018 Não encontrada!
Data 27/10/2018 Não encontrada!


In [50]:
#Atribuindo à variável dataSet o DataFrame atualizado
dataSet = dataSet00
#Verificando dimensões do DataFrame
print(dataSet.shape)

(13502, 8)


In [0]:
#Transformando a coluna Data de volta em uma coluna de informações do dataSet
dataSet = dataSet.reset_index()

In [52]:
#Eliminando da base de dados dias que não tenham ao menos 5 das variáveis no dataSet
dataSet = dataSet.dropna(thresh=5)
#Exibindo novas dimensões da base de dados
print(dataSet.shape)

(13455, 9)


# Considerando os seguintes intervalos: 
- Outono: 20 de março a 21 de junho (fechado em 20/03 e aberto em 21/06)
- Inverno: 21 de junho a 22 de setembro (fechado em 21/06 e aberto em 22/09)
- Primavera: de 22 de setembro a 21 de dezembro (fechado em 22/09 e aberto em 21/12)
- Verão: de 21 de dezembro a 20 de março (fechado em 21/12 e aberto em 20/03)

In [0]:
#Função que retorna a estação do ano para uma determinada data, para ser adicionada à base de dados
def season(data):
    if (data.month > 3 and data.month < 6) or (data.month == 3 and data.day >= 20) or (data.month == 6 and data.day < 21):
        return "Out"
    if (data.month > 6 and data.month < 9) or (data.month == 6 and data.day >= 21) or (data.month == 9 and data.day < 22):
        return "Inv"
    if (data.month > 9 and data.month < 12) or (data.month == 9 and data.day >= 22) or (data.month == 12 and data.day < 21):
        return "Pri"
    else:
        return "Ver"

In [0]:
#Identificando a estação do ano na base de dados e guardando a informação referente ao ano de cada dado
estacao = []
for i in dataSet.index:
    estacao.insert(i, season(dataSet.loc[i, "Data"]))

In [55]:
#Contando quantos dados existem para cada estação
print("Outono: " + str(estacao.count("Out")))
print("Inverno: " + str(estacao.count("Inv")))
print("Primavera: " + str(estacao.count("Pri")))
print("Verão: " + str(estacao.count("Ver")))

Outono: 3397
Inverno: 3460
Primavera: 3337
Verão: 3261


In [56]:
#Eliminando a coluna "Data" e visualizando dados
dataSet = dataSet.drop(columns="Data")
dataSet.head()

Prec  TempMax  TempMin  Insolacao  EvapoPiche  TempCompMedia  \
0   0.0     30.6     21.4       11.1         4.4          25.14   
1   0.0     31.0     19.6       11.9         6.5          24.92   
2   0.0     31.6     18.5       11.3         5.0          24.90   
3   0.0     31.2     20.7       10.3         4.0          24.82   
4   0.0     30.8     19.9       11.0         4.2          24.78   

   UmidRelatMedia  VelocVento  
0           73.50    2.666667  
1           74.75    1.666667  
2           77.25    2.333333  
3           80.75    3.666667  
4           76.00    4.000000

(13455, 8)


In [0]:
#Decodificando as estações em uma matriz (one hot encoding - dummy variables)
encoder = LabelEncoder()
encoder.fit(estacao)
encodedSeason = encoder.transform(estacao)
dummySeason = np_utils.to_categorical(encodedSeason)

In [20]:
#Identificar como aconteceu a transformação
auxSeason = encoder.transform(["Inv","Out","Pri","Ver"])
auxDummy = np_utils.to_categorical(auxSeason)
print("[Inv,Out,Pri,Ver]")
print(auxDummy)

[Inv,Out,Pri,Ver]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
#Exibindo dataSet após as modificações
dataSet.head()

Prec  TempMax  TempMin  Insolacao  EvapoPiche  TempCompMedia  \
0   0.0     30.6     21.4       11.1         4.4          25.14   
1   0.0     31.0     19.6       11.9         6.5          24.92   
2   0.0     31.6     18.5       11.3         5.0          24.90   
3   0.0     31.2     20.7       10.3         4.0          24.82   
4   0.0     30.8     19.9       11.0         4.2          24.78   

   UmidRelatMedia  VelocVento  
0           73.50    2.666667  
1           74.75    1.666667  
2           77.25    2.333333  
3           80.75    3.666667  
4           76.00    4.000000

In [0]:
#Separando a variável que será prevista, precipitação, da base de dados
prec = dataSet["Prec"]
dataSet = dataSet.drop(columns = "Prec")

In [23]:
#Adicionando ao dataSet as informações de estação climática
dataSet["Inv"] = dummySeason[:,0]
dataSet["Out"] = dummySeason[:,1]
dataSet["Pri"] = dummySeason[:,2]
dataSet["Ver"] = dummySeason[:,3]

ValueError: ignored

In [0]:
#Efetuando uma transformação do tipo: z = (x - u) / s, normalizando em termos do desvio padrão
sc = StandardScaler()
dataSet = sc.fit_transform(dataSet)
#X_test[:,:-2] = sc.transform(X_test[:,:-2])

In [53]:
print(prec.isnan())

AttributeError: ignored

In [0]:
#Separando conjunto de treino e teste
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, random_state = 1)

In [0]:
#Visualizando o conjunto de treino
print(X_train)
print(X_train.shape)

In [0]:
#Efetuando uma transformação do tipo: z = (x - u) / s, normalizando em termos do desvio padrão
sc = StandardScaler()
X_train[:,:-2] = sc.fit_transform(X_train[:,:-2])
X_test[:,:-2] = sc.transform(X_test[:,:-2])

In [0]:
#Verificando os dados de treino após a transformação
print(X_train)

In [0]:
#Criando um modelo de MLP
mlp = Sequential()
#Adicionando a camada de entrada
mlp.add(Dense(activation = 'relu', input_dim = len(X_train[0]), units = 40, kernel_initializer = 'uniform'))
#Adicionando a segunda camada
mlp.add(Dense(activation = 'relu', units = 20, kernel_initializer = 'uniform'))
#Adicionando a terceira camada
mlp.add(Dense(activation = 'relu', units = 10, kernel_initializer = 'uniform'))
#Adicionando a quarta camada
mlp.add(Dense(activation = 'relu', units = 5, kernel_initializer = 'uniform'))
#Adicionando a camada de saída
mlp.add(Dense(units = 1, kernel_initializer='normal'))
# Compilando o modelo
mlp.compile(loss='mse', optimizer='adam', metrics=['mse','mae'])
#Mostrando um sumário do modelo de MLP criada
mlp.summary()

In [0]:
#Treinando a MLP rede, a partir do modelo de MLP criado
rede = mlp.fit(X_train, Y_train, epochs=100, verbose=1, validation_split=0.1)

In [0]:
#Mostrando o processo de treino graficamente
plt.plot(rede.history['loss'])
plt.plot(rede.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.ylim(0,1)
plt.legend(['train', 'validation'], loc='upper left')
plt.show()

In [0]:
#Fazendo uma previsão com base nos dados de teste
Y_previsto = mlp.predict(X_test)

In [0]:
#Mostrando o array de dados previstos
print(Y_previsto)

In [0]:
#Mostrando o array de dados reais que deveriam ter sido previstos no passo anterior
print(Y_test)

In [0]:
#Calculando e mostrando o erro mínimo quadrático entre o Y previsto e o Y real
print(mean_squared_error(Y_previsto, Y_test))